/**
 * This file is auto generated by the grunt `compile-templates` task.
 */

module.exports.entry = require('../../../partials/slides/entry.hbs');
module.exports.followAlong = require('../../../partials/slides/followAlong.hbs');
module.exports.gettingSetUp = require('../../../partials/slides/gettingSetUp.hbs');
module.exports.gettingSetUpConsole = require('../../../partials/slides/gettingSetUpConsole.hbs');
module.exports.gettingSetUpGrunt = require('../../../partials/slides/gettingSetUpGrunt.hbs');
module.exports.gettingSetUpNonNpmDeps = require('../../../partials/slides/gettingSetUpNonNpmDeps.hbs');
module.exports.gettingSetUpPackageJson = require('../../../partials/slides/gettingSetUpPackageJson.hbs');
module.exports.gettingSetUpShimmingCommonJSModules = require('../../../partials/slides/gettingSetUpShimmingCommonJSModules.hbs');
module.exports.gettingSetUpShimmingGlobals = require('../../../partials/slides/gettingSetUpShimmingGlobals.hbs');
module.exports.gettingSetUpUnderstandingTransforms = require('../../../partials/slides/gettingSetUpUnderstandingTransforms.hbs');
module.exports.marionette = require('../../../partials/slides/marionette.hbs');
module.exports.marionetteAppConfig = require('../../../partials/slides/marionetteAppConfig.hbs');
module.exports.marionetteAppStart = require('../../../partials/slides/marionetteAppStart.hbs');
module.exports.marionetteConfigInit = require('../../../partials/slides/marionetteConfigInit.hbs');
module.exports.marionetteKeepThingsSmall = require('../../../partials/slides/marionetteKeepThingsSmall.hbs');
module.exports.marionetteKeepThingsSmallTitle = require('../../../partials/slides/marionetteKeepThingsSmallTitle.hbs');
module.exports.marionetteModules1 = require('../../../partials/slides/marionetteModules1.hbs');
module.exports.marionetteModulesOldWay = require('../../../partials/slides/marionetteModulesOldWay.hbs');
module.exports.marionetteModulesTitle = require('../../../partials/slides/marionetteModulesTitle.hbs');
module.exports.marionetteTemplates1 = require('../../../partials/slides/marionetteTemplates1.hbs');
module.exports.marionetteTemplates2 = require('../../../partials/slides/marionetteTemplates2.hbs');
module.exports.marionetteWorkingWithTemplates = require('../../../partials/slides/marionetteWorkingWithTemplates.hbs');
module.exports.moar = require('../../../partials/slides/moar.hbs');
module.exports.resources = require('../../../partials/slides/resources.hbs');
module.exports.soDry = require('../../../partials/slides/soDry.hbs');
module.exports.soDry1 = require('../../../partials/slides/soDry1.hbs');
module.exports.soDry2 = require('../../../partials/slides/soDry2.hbs');
module.exports.whatIs = require('../../../partials/slides/whatIs.hbs');
module.exports.whatIsQuote = require('../../../partials/slides/whatIsQuote.hbs');
module.exports.whyUse = require('../../../partials/slides/whyUse.hbs');
module.exports.whyUseBuildIntegration = require('../../../partials/slides/whyUseBuildIntegration.hbs');
module.exports.whyUseCommonJS = require('../../../partials/slides/whyUseCommonJS.hbs');
module.exports.whyUseNpmModules = require('../../../partials/slides/whyUseNpmModules.hbs');
